import "./SuggestionCard.css";

function SuggestionCard() {

    const suggestions = [

        {
            priority: "High",
            icon: "🚨",
            title: "Conduct Mentoring Session",
            description:
                "12 students have attendance below 75%. Schedule a mentoring session within this week."
        },

        {
            priority: "Medium",
            icon: "📚",
            title: "Assignment Follow-up",
            description:
                "8 students haven't submitted their latest assignment."
        },

        {
            priority: "Low",
            icon: "🎯",
            title: "Improve Test Performance",
            description:
                "Average test score dropped by 6%. Consider conducting a revision lecture."
        }

    ];

    return (

        <div className="suggestion-card">

            <div className="suggestion-header">

                <h3>💡 AI Recommendations</h3>

                <span>Generated by Saarthi AI</span>

            </div>

            <div className="suggestion-list">

                {

                    suggestions.map((item,index)=>(

                        <div
                            key={index}
                            className={`suggestion-item ${item.priority.toLowerCase()}`}
                        >

                            <div className="suggestion-icon">

                                {item.icon}

                            </div>

                            <div className="suggestion-content">

                                <div className="suggestion-title">

                                    {item.title}

                                </div>

                                <p>

                                    {item.description}

                                </p>

                                <span className="priority">

                                    {item.priority} Priority

                                </span>

                            </div>

                        </div>

                    ))

                }

            </div>

        </div>

    );

}

export default SuggestionCard;